version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - todo-mysql-data:/var/lib/mysql

  app:
    build: .
    environment:
      MYSQL_HOST: db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: 1234
      MYSQL_DB: app_db
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  todo-mysql-data:
